version: '3.9'

services:
  app:
    build: .
    container_name: team-collab-app
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: sh -c "npx prisma migrate dev --name init && node index.js"

  db:
    image: postgres:15
    container_name: team-collab-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: team_collab
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
