version: '3.9'

services:
  app:
    build: .
    container_name: team-collab-app
    ports:
      - '5555:5555'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=5555
    command: sh -c "npx prisma migrate dev --name init && npm run seed && node index.js"

  client:
    image: node:18
    container_name: team-collab-client
    ports:
      - '3001:3001'
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - PORT=3001
    command: sh -c "npm install && npm start"
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: team-collab-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: team_collab
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
