#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Lint backend
npx eslint . --ext .js

# Lint frontend
cd client && npx eslint src --ext .js,.jsx && cd ..

# Prettier check
npx prettier --check .